#!/bin/bash

# -- every variable can be overridden from the environment, e.g.,
#
#      PETSC_PFX=/scratch/me/petsc ./build.sh

: "${UKRMOL_ROOT:=${HOME}/.local}"
[ -n "$UKRMOL_ROOT" ] || { echo "buildcfg: UKRMOL_ROOT empty" >&2; return 1 2>/dev/null || exit 1; }

# -- installation prefixes
: "${MPICH_PFX:=${UKRMOL_ROOT}/mpich}"
: "${OPENBLAS_PFX:=${UKRMOL_ROOT}}"
: "${SCALAPACK_PFX:=${UKRMOL_ROOT}/scalapack64}"
: "${PETSC_PFX:=${UKRMOL_ROOT}/petsc64}"
: "${SLEPC_PFX:=${UKRMOL_ROOT}/slepc64}"
: "${UKRMOL_IN_PFX:=${UKRMOL_ROOT}/ukrmol-in}"
: "${UKRMOL_OUT_PFX:=${UKRMOL_ROOT}/ukrmol-out}"

# -- variables used by the installation scripts, can also be overridden
: "${MAKEJOBS:=$(nproc)}" # so we dont always use nprocs (e.g., on login nodes)
: "${MPI_HOME:=${MPICH_PFX}}"
: "${OPENBLAS_INC:=${OPENBLAS_PFX}/include}"
: "${GBTO_INC:=${UKRMOL_IN_PFX}/include/ukrmol-in/gbtolib}"
: "${GBTO_LIB:=${UKRMOL_IN_PFX}/lib/ukrmol-in/libGBTO.a}"
: "${LIBDIR:=lib}" # <-- install libdir name. Some cmakes default to lib64, others to lib
: "${OPENBLAS_LIB:=${OPENBLAS_PFX}/${LIBDIR}}"
: "${SCALAPACK_LIB:=${SCALAPACK_PFX}/${LIBDIR}/libscalapack.so}"

: "${CMAKE:=cmake}"

# -- compilation commands (can be overridden)
: "${MPICC:=$MPI_HOME/bin/mpicc}"
: "${MPICXX:=$MPI_HOME/bin/mpicxx}"
: "${MPIFORT:=$MPI_HOME/bin/mpifort}"
: "${MPIEXEC:=$MPI_HOME/bin/mpiexec}"

# -- export them all
export UKRMOL_ROOT
export MPICH_PFX
export OPENBLAS_PFX
export SCALAPACK_PFX
export PETSC_PFX
export SLEPC_PFX
export UKRMOL_IN_PFX
export UKRMOL_OUT_PFX
export MPI_HOME
export OPENBLAS_LIB
export OPENBLAS_INC
export SCALAPACK_LIB
export GBTO_INC
export GBTO_LIB
export CMAKE
export MPICC
export MPICXX
export MPIFORT
export MPIEXEC
export MAKEJOBS
export LIBDIR
